### ISSUE TITLE
How can I use it correctly

### ISSUE THREAD

**Issue by linglong233** [L0serQianXia/LetsUseNativeObfuscator#4]
I should use it as written in the Wiki and put letusenativeobfuscator jar, jni. h, jni_ md.h, jvmti. Put h in < dir > / CPP, and I run Java - jar letusenativeobfuscator with CMD The following message appears after jar

`_____________LetsUseNativeObfuscator v1.23_____________

   This is a tool to help you compiler the source
   that created by NativeObfuscator
   (https://github.com/radioegor146/native-obfuscator)

   https://github.com/L0serQianXia/LetsUseNativeObfuscator

   !!!you should install Mingw-w64(http://mingw-w64.org/) first!!!

_____________LetsUseNativeObfuscator v1.23_____________
[INFO]Compiling the CPP files
[DEBUG]g++ -m32 -c ".\native_jvm.cpp" -o ".\x32/native_jvm.o"
[DEBUG]1
[DEBUG]g++ -m32 -c ".\native_jvm_output.cpp" -o ".\x32/native_jvm_output.o"
[DEBUG]2
[DEBUG]g++ -m32 -c ".\string_pool.cpp" -o ".\x32/string_pool.o"
[DEBUG]3`

**Comment by linglong233** [comment]
I installed MinGW

**Comment by L0serQianXia** [comment]
上面的输出信息是固定不变的，它并不会检测你是否安装了MinGW。是否有更多的输出信息？或是进程有异常退出？

**Comment by linglong233** [comment]
我这边的环境在msys运行就好了，可能我哪没配置对。
十分感谢回复，我前几天不在家没看GitHub的消息，不好意思了

**Comment by L0serQianXia** [comment]
好



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月4日(星期一) 晚上8:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [L0serQianXia/LetsUseNativeObfuscator] How can I use it correctly (Issue #4)





 
我这边的环境在msys运行就好了，可能我哪没配置对。
 十分感谢回复，我前几天不在家没看GitHub的消息，不好意思了
