### ISSUE TITLE
在处理cpp文件的时候总是卡在最后一个cpp

### ISSUE THREAD

**Issue by nuym** [L0serQianXia/LetsUseNativeObfuscator#5]
![image](https://user-images.githubusercontent.com/102905510/184645311-2702f0e8-f161-4723-a062-f3ea0e81935c.png)
如图，无论换哪个jar都是卡在最后一个 1.2.3 和 1.2.2一样，图为1.2.2

**Comment by L0serQianXia** [comment]
可能是由于gcc执行出现错误，请使用1.3版本得到将执行的命令，之后在命令提示符中执行查看是否有输出

**Comment by nuym** [comment]
执行的命令为:g++ -m32 -shared .\x32\string_pool.o  -static-libstdc++ -static-libgcc -lwinpthread -Bdynamic -o x32/My32DLL.dll
在 CMD 运行中反馈 collect2.exe: error: ld returned 1 exit status

**Comment by L0serQianXia** [comment]
是否有在`\cpp`目录（`LetsUseNativeObfuscator.jar`所在目录）放置`jni.h`, `jni_md.h`, `jvmti.h`？如果没有，请放置后重新执行`java -jar LetsUseNativeObfuscator.jar`

**Comment by nuym** [comment]
请问这些文件在哪里获得

**Comment by L0serQianXia** [comment]
<JDK_PATH>/include/jni.h
<JDK_PATH>/include/win32/jni_md.h
jvmti.h应该不需要

**Comment by nuym** [comment]
仍然输出g++ -m32 -shared .\x32\cn_nuym_magnolia_Magnolia_0.o .\x32\native_jvm.o .\x32\native_jvm_output.o .\x32\string_pool.o  -static-libstdc++ -static-libgcc -lwinpthread -Bdynamic -o x32/My32DLL.dll
CMD反馈collect2.exe: error: ld returned 1 exit status

**Comment by nuym** [comment]
请问您有联系方式吗，可以远程一下看看？

**Comment by L0serQianXia** [comment]
向日葵可以吗

**Comment by nuym** [comment]
可以 我的识别码:683341127
使用向日葵即可对我发起远程协助
向日葵下载地址:http://url.oray.com/tGJdas/

**Comment by L0serQianXia** [comment]
通过远程发现主要问题：MinGW版本，推荐使用[x86_64-8.1.0-release-posix-sjlj-rt_v6-rev0.7z](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/sjlj/x86_64-8.1.0-release-posix-sjlj-rt_v6-rev0.7z)解决问题
其次是本项目对无主类文件的支持并不好，此问题已尝试在1.4版中修复
若有新问题请提新issue，感谢反馈
