### ISSUE TITLE
java.util.zip.ZipException: duplicate entry

### ISSUE THREAD

**Issue by nuym** [L0serQianXia/LetsUseNativeObfuscator#6]
很抱歉再次打扰到你
![image](https://user-images.githubusercontent.com/102905510/185787645-07d7d8da-6ce0-4ffb-b2c6-e3f85c135772.png)

**Comment by L0serQianXia** [comment]
查看cpp目录的父级目录，检查目录中的Jar文件，通常在将一个处理过的Jar文件再次处理时，会出现这些报错

**Comment by nuym** [comment]
![image](https://user-images.githubusercontent.com/102905510/185788047-d6c4971e-a625-4e95-9763-0b9a11561ddb.png)
完美运行 谢谢❤❤❤

**Comment by L0serQianXia** [comment]
确实是因为代码很烂，人很懒，没有写明确的反馈信息，也感谢你提的issue让我发现许多问题，有任何问题请随时提issue❤
