### ISSUE TITLE
无法在其他Windows系统上运行？

### ISSUE THREAD

**Issue by nuym** [L0serQianXia/LetsUseNativeObfuscator#7]
在更换其他Windows系统下运行时缺少dll文件
![image](https://user-images.githubusercontent.com/102905510/185793511-d95b65f9-a84b-48b7-b37c-a14d490ec39c.png)
DllDepends是否补全？
![TUU7%)2 4_A2TK0K%P%D6$Q](https://user-images.githubusercontent.com/102905510/185793548-54ab3475-3ad0-45e8-81ac-56dc0f34d81e.png)
能否在未来支持Linux?

**Comment by L0serQianXia** [comment]
略早期版本中，这个DLL问题是被解决了的，但在一个commit中（[ae33f705d87a9a7d8804f05dd06671a3619302be](https://github.com/L0serQianXia/LetsUseNativeObfuscator/commit/ae33f705d87a9a7d8804f05dd06671a3619302be)），我认为部分编译参数无用而将其移除，这个问题就出现了。将在1.41版本中修复。
对于Linux暂不考虑支持

（上学了键盘都落灰了，没回复对不起![`JVE${ZY{BCFMD }B97R)A9](https://user-images.githubusercontent.com/39728106/194115981-400bd736-f8b9-452f-858d-28afbd2cab0c.png)）

**Comment by L0serQianXia** [comment]
1.41版本已发布
